### ISSUE TITLE
Port cc!tempban to v13

### ISSUE THREAD

**Issue by mikejoh12** [CodecademyCommunity/codecademy-discord-bot#248]

**Comment by Victoria-DR** [comment]
Before someone works on this, I think it's worth discussing whether we should even do this. The tempban command currently has an issue where it doesn't unban the user after the specified amount of time due to it resetting when the bot crashes (see #165). Considering that we haven't ever even attempted to use the command because there isn't much use for it (infractions usually result in mutes or permanent bans), I would be in favour of completely scrapping this command and moving it to the archives. What are your thoughts everyone?

**Comment by lyallstewart** [comment]
Closed by #255
